services:
  backstage-pyactions:
    build: .
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    env_file:
      - .env
    volumes:
      - ./modules.yaml:/app/modules.yaml
      - ./app/modules:/app/app/modules
      - ./app/templates:/app/app/templates
